services:
  react-app:
    image: my-portfolio
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev