name: Deploy to Firebase Hosting
on:
    push:
        branches:
            - main # main branch

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: CI=false npm run build #CI=false to disable eslint for build

            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}" # personal access token
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" # firebase service account
                  channelId: live # This is the firebase channel and live is the default
                  projectId: yevhen-portfolio-page # project id from firebase
