name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: CI=false npm run build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_API_AUTH_DOMAIN: ${{ secrets.VITE_API_AUTH_DOMAIN }}
          VITE_API_PROJECT_ID: ${{ secrets.VITE_API_PROJECT_ID }}
          VITE_API_STORAGE_BUCKET: ${{ secrets.VITE_API_STORAGE_BUCKET }}
          VITE_API_MESSAGING_SENDER_ID: ${{ secrets.VITE_API_MESSAGING_SENDER_ID }}
          VITE_API_APP_ID: ${{ secrets.VITE_API_APP_ID }}
          VITE_PUBLIC_KEY: ${{ secrets.VITE_PUBLIC_KEY }}
          VITE_TEMPLATE_ID: ${{ secrets.VITE_TEMPLATE_ID }}
          VITE_SERVICE_ID: ${{ secrets.VITE_SERVICE_ID }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: yevhen-portfolio-page